<?php
	$this->headTitle('Admin');
?>

<h1>Admin</h1>

<div class='admin-infoblock'>
    <div class='header'>
        <span class="title">Recently Added Pages</span>
        <span class="extra"><a href="/admin/pages/add">New Page</a> | <a href="/admin/pages">View All</a></span>
    </div>
    <div class='content'>
        <?php echo $this->partialLoop('_partials/admin/index/infoblock-pages.phtml', $this->pages); ?>
    </div>
</div>
