<tr>
	<td><a href="/admin/pages/edit/page/<?= $this->id; ?>"><?= $this->name; ?></a></td>
	<td align="center"><?= $this->parent_page; ?></td>
	<td align="center"><?= $this->module; ?></td>
	<td align="center"><a href="/admin/pages/changestatus/page/<?= $this->id; ?>"><?= ($this->active ? 'Active' : 'Inactive'); ?></a></td>
	<td align="center"><a href="/admin/pages/settings/page/<?= $this->id; ?>"><img src="/images/admin/settings.png" border="0"></a></td>
	<td align="center"><a href="/admin/pages/delete/page/<?= $this->id; ?>"><img src="/images/admin/delete.png" border="0"></a></td>
	<td align="center"><a href="/admin/pages/sethomepage/page/<?= $this->id; ?>"><?= ($this->homepage ? 'Yes' : 'No'); ?></a></td>
</tr>
