<?php
	$this->headTitle('Please Log In');
?>

<h1>Please log in</h1>

<font color="red"><b><?= $this->errorMessage; ?></b></font>

<form method="post">
	<table>
		<tr>
			<td>Username:</td>
			<td><input type="text" name="username"></td>
		</tr>
		<tr>
			<td>Password:</td>
			<td><input type="password" name="passwd"></td>
		</tr>
		<tr>
			<td colspan="2" align="right"><input type="submit" name="login"></td>
		</tr>
	</table>
</form>
