<script type="text/javascript" src="/js/fckeditor/fckeditor.js"></script>
<script type="text/javascript">
	function initEditor() {
		var oFCKeditor = new FCKeditor( 'pageText' ) ;
		oFCKeditor.BasePath = "/js/fckeditor/" ;
	}
	
	$(document).ready(function() {
		initEditor();
	});
</script>

<form method="post">
	<textarea name="pageText" cols="75" rows="20"><?= $this->existingText; ?></textarea>
	
	<p>
	<input type="submit" name="save" value="Save">
</form>
