<script type="text/javascript" src="/js/fckeditor/fckeditor.js"></script>
<script type="text/javascript">
	function initEditor() {
		var oFCKeditor = new FCKeditor( 'pageText' ) ;
		oFCKeditor.BasePath = "/js/fckeditor/" ;
		oFCKeditor.Height = '500';
	    oFCKeditor.ReplaceTextarea();
		
	}
	
	$(document).ready(function() {
		initEditor();
	});
</script>

<form method="post" action="/admin/pages/edit/page/<?php echo $this->id; ?>">
	<textarea name="pageText" cols="75" rows="50"><?= $this->existingText; ?></textarea>
	
	<p>
	<input type="submit" name="save" value="Save">
</form>
