<form method="post">
<table>
	<tr>
		<td>Link Name:</td>
		<td><input type="text" name="linkName" value="<?= $this->linkName; ?>"></td>
	</tr>
	<tr>
		<td>Module:</td>
		<td><input type="text" name="module" value="<?= $this->module; ?>"></td>
	</tr>
	<tr>
		<td>Controller:</td>
		<td><input type="text" name="controller" value="<?= $this->controller; ?>"></td>
	</tr>
	<tr>
		<td>Action:</td>
		<td><input type="text" name="action" value="<?= $this->action; ?>"></td>
	</tr>
	<tr>
		<td>Params:</td>
		<td><input type="text" name="params" value="<?= $this->params; ?>"></td>
	<tr>
		<td colspan="2" align="right"><input type="submit" value="Save"></td>
	</tr>
</table>
</form>
