<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">

<html>
<head>
<?php
	$this->headTitle()->prepend('Kiroku');
	$this->headTitle()->setSeparator(' :: ');
	print $this->headTitle();
?>

	<script type="text/javascript" src="/js/jquery/jquery-1.3.2.min.js"></script>
	<script type="text/javascript" src="/js/jquery/jquery-ui-1.7.2.custom.min.js"></script>
	<?= $this->headScript(); ?>
	
	<link rel="stylesheet" href="/css/jquery/redmond/jquery-ui-1.7.2.custom.css" type="text/css">
	<link rel="stylesheet" href="/themes/default/css/reset-fonts-grids.css" type="text/css">
	<link rel="stylesheet" href="/themes/default/css/base-min.css" type="text/css">
	<link rel="stylesheet" type="text/css" href="/themes/default/css/admin.css">
	<?= $this->headLink(); ?>
</head>

<body>
<div id="doc3" class="yui-t7">
	<div id="hd-nav">
		<p class="callsign">
			<a href="/admin">KIROKU</a>
		</p>
        <ul>
        	<li><a href="/auth/index/logout">Log Out</a></li>
        	<li><a href="/admin/users">Users</a></li>
        	<li><a href="/admin/system">System Config</a></li>
        	<li><a href="/admin/sections">Sections</a></li>
        	<li><a href="/admin/modules">Plugins</a></li>
            <li><a href="/admin/pages">Pages</a></li>
            <li><a href="/">View Site</a></li>
        </ul>
	</div>
	<div id="bd">
        <div class="yui-g" id="content">
			<!-- YOUR DATA GOES HERE -->
			<?= $this->layout()->content; ?>
		</div>
	</div>
	<div id="ft"><a href="http://blogs.tankersleywebsolutions.com">Kiroku - Copyright 2009 Chris Tankersley</a></div>
</div>
</body>
</html>
