<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">

<html>
<head>
<?php
	$this->headTitle()->prepend('Kiroku');
	$this->headTitle()->setSeparator(' :: ');
	print $this->headTitle();
?>

	<script type="text/javascript" src="/js/jquery/jquery-1.3.2.min.js"></script>
	<script type="text/javascript" src="/themes/default/js/jquery.reverseorder.packed.js"></script>
	<script type="text/javascript">
		$(document).ready(function() {
			$('#nav-list').reverseOrder();
		});
	</script>
	<?= $this->headScript(); ?>
	
	<link rel="stylesheet" href="/themes/default/css/reset-fonts-grids.css" type="text/css">
	<link rel="stylesheet" href="/themes/default/css/base-min.css" type="text/css">
    <link rel="stylesheet" type="text/css" href="/themes/default/style.css">
	<?= $this->headLink(); ?>
</head>

<body>
<div id="doc3" class="yui-t7">
	<div id="hd">
		<img alt="Kiroku Logo" src="/themes/default/images/logo.png" />

		<div id="nav">
			<ul id="nav-list">
				<?php echo $this->mainMenu(true); ?>
			</ul>
		</div>
		
	</div>

	<div id="bd">
        <div class="yui-g">
			<!-- YOUR DATA GOES HERE -->
			<?= $this->layout()->content; ?>
		</div>
	</div>
	<div id="ft"><a href="http://blogs.tankersleywebsolutions.com">Kiroku - Copyright 2009 Chris Tankersley</a></div>
</div>
</body>
</html>
