<?php $this->headTitle('Section Administration'); ?>
<script type="text/javascript">
	function changeStatus(id) {
		$.ajax({
			data: { 'id': id },
			dataType: 'json',
			error: function(rqs, status, error) {
				alert('There was a problem changing the status of the section.');
			},
			success: function(rsp) {
				if(rsp.success == 1) {
					alert('Default section has been updated');
					window.location = '/admin/sections';
				} else {
					alert(rsp.message);
				}
			},
			type: 'GET',
			url: '/admin/sections/changestatus/'
		});
	}
	
	function installPlugin(name)
	{
		$.ajax({
			data: { 'name' : name },
			dataType: 'json',
			error: function(rqs, status, error) {
				alert('There was a problem calling the installer for the ' + name + ' section.');
			},
			success: function(rsp) {
				if(rsp.status) {
					alert('Section ' + name + ' has been installed.');
					window.location = '/admin/sections';
				} else {
					alert('There was a problem installing ' + name);
				}
			},
			type: 'GET',
			url: '/admin/sections/install/'
		});
	}
	
	function uninstallPlugin(name)
	{
		$.ajax({
			data: { 'name' : name },
			dataType: 'json',
			error: function(rqs, status, error) {
				alert('There was a problem calling the uninstaller for the ' + name + ' section.');
			},
			success: function(rsp) {
				if(rsp.status) {
					alert('Section ' + name + ' has been uninstalled.');
					window.location = '/admin/sections';
				} else {
					alert('There was a problem uninstalling ' + name + '. There error was:\n' + rsp.message);
				}
			},
			type: 'GET',
			url: '/admin/sections/uninstall/'
		});
	}
	
	$(document).ready(function() {
		$('.stripped tr:even').addClass('evenRow');
	});
</script>

<h1>Section Administration</h1>

<h2>Installed Sections</h2>

<table class="stripped" cellspacing="0" width="100%">
	<thead>
		<tr>
			<th>Name</th>
			<th>Description</th>
			<th>Default Section</th>
			<th>Uninstall</th>
		</tr>
	</thead>
	<tbody>
		<?php echo $this->partialLoop('sections/_partials/installedModules.phtml', $this->installedModules);?>
	</tbody>
</table>

<h2>Uninstalled Sections</h2>

<table class="stripped" cellspacing="0" width="100%">
	<thead>
		<tr>
			<th>Name</th>
			<th>Install</th>
		</tr>
	</thead>
	<tbody>
		<?php echo $this->partialLoop('sections/_partials/uninstalledModules.phtml', $this->uninstalledModules);?>
	</tbody>
</table>
